#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "  Customized add:"
  echo "    add pri PRIORITY \"THING I NEED TO DO +project @context\""
  echo "    add p PRIORITY \"THING I NEED TO DO +project @context\""
  echo "      add an item and prioritize it in one step"
  echo "    add x \"THING I NEEDED TO DO RIGHT NOW\""
  echo "      add an item and mark it as done in one step"
  echo ""
  exit
}

PRIORITY=false
DO=false
TODOLINE="$@"
if [ x"$1" = x"pri" -o x"$1" = x"p" ] && [[ x"$2" = x[a-zA-Z] ]]; then
    PRIORITY=$2
    shift
    shift
    TODOLINE="($PRIORITY) $@"
elif [ x"$1" = x"x" ]; then
    DO=true
    shift
    TODOLINE="$@"
fi

# call back to the main script to add
if "$TODO_SH" command add "$TODOLINE"; then
    # figure out the line of what we just added, and "do" it
    line=`sed -n '$ =' "$TODO_FILE"`
    $DO && "$TODO_SH" command do "$line"
fi
