#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "    addx"
  echo "      add an item and mark it as done in one step"
  echo ""
  exit
}

. $TODOTXT_CFG_FILE
# call back to the main script to add
echo $TODOTXT_SH add "$@"
if $TODOTXT_SH add "$@"; then
    # figure out the line of what we just added, and "do" it
    line=`wc -l "$TODO_FILE" | cut -d' ' -f1`
    $TODOTXT_SH do "$line"
fi
