#!/bin/bash

action=$1
shift

function usage(){
  echo "  Edit line:"
  echo "    edit ITEM#"
  echo ""
  exit
}

[ "$action" = "usage" ] && usage

. "$TODOTXT_CFG_FILE"

if ! [[ "$1" =~ ^[0-9]+$ ]]; then
    echo "Error! Usage:"
    usage
fi

${EDITOR:-vi} +$1 "$TODO_FILE"
