#!/bin/bash

action=$1
shift

function usage(){
  echo "  Navigate to URL:"
  echo "    nav ITEM#"
  echo "      Searches for a URL in the todo line and launches a browser."
  echo ""
  exit
}

[ "$action" = "usage" ] && usage

. "$TODOTXT_CFG_FILE"

if ! [[ "$1" =~ ^[0-9]+$ ]]; then
    echo "Error! Usage:"
    usage
fi

URL=$(sed "$1!d" "$TODO_FILE"|grep -E -o "(https?|ftp)://[^ ]+")
if [ "$URL" = "" ]; then
    LINE=$(sed "$1!d" "$TODO_FILE")
    if [ "$LINE" = "" ]; then
        echo "Error, no item #$1 found!"
    else
        echo "Error, no URL seen in item #$1!"
        echo "$LINE"
    fi
    exit 1
fi

# Trying to be smart...
# on Debian alike:
if $(which x-www-browser >/dev/null); then
    exec x-www-browser "$URL"
# if you have git:
elif [ -x /usr/lib/git-core/git-web--browse ]; then
    cd /usr/lib/git-core && ./git-web--browse "$URL"
# last resort, a la mano...
elif $(which firefox >/dev/null); then
    exec firefox "$URL"
elif $(which konqueror >/dev/null); then
    exec konqueror "$URL"
elif $(which nautilus >/dev/null); then
    exec nautilus "$URL"
else
    echo "Sorry I'm giving up, cannot find your browser :-("
fi
